apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: s4-data
  labels:
    app: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
# Uncomment to enable local file browser (also uncomment volumeMount and volume in deployment)
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: s4-local-storage
#   labels:
#     app: s4
#     app.kubernetes.io/name: s4
#     app.kubernetes.io/component: storage
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 50Gi
