apiVersion: v1
kind: Service
metadata:
  name: s4
  labels:
    app: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/component: storage
spec:
  type: ClusterIP
  ports:
    - name: s3-api
      port: 7480
      targetPort: 7480
      protocol: TCP
    - name: web-ui
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: s4
---
apiVersion: v1
kind: Service
metadata:
  name: s4-nodeport
  labels:
    app: s4
    app.kubernetes.io/name: s4
    app.kubernetes.io/component: storage
spec:
  type: NodePort
  ports:
    - name: s3-api
      port: 7480
      targetPort: 7480
      protocol: TCP
    - name: web-ui
      port: 5000
      targetPort: 5000
      protocol: TCP
  selector:
    app: s4
